// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITaskSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITaskSystem {
  function app__addTask(uint256 id, string memory description) external;

  function app__completeTask(uint256 id) external;

  function app__resetTask(uint256 id) external;

  function app__deleteTask(uint256 id) external;
}
